[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bootcampdapp = "EJhsvpPeCpUChwyDEcKyJCLorDb89q1cfY4HPwutzF6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cd .. && npx vitest run anchor/tests/**"
